// blog.js
// Drives the homepage: populates the hero's masthead meta line, and
// renders the in-page Blog section (fixed "most recent" feature card
// plus a searchable/filterable grid of every other post) from
// posts-index.json (generated by build.js). No dependencies.

document.addEventListener("DOMContentLoaded", async () => {
  // This script is shared by the homepage (index.html, at the site root)
  // and the standalone blog listing (blog/index.html, one level down),
  // so paths have to adapt to wherever the page actually lives.
  const inBlogDir = /\/blog\/(?:index\.html)?$/.test(window.location.pathname);
  const postsIndexPath = inBlogDir ? "../posts-index.json" : "posts-index.json";
  const postLinkPrefix = inBlogDir ? "" : "blog/";

  const mastheadMeta = document.getElementById("masthead-meta");
  const featuredContainer = document.getElementById("featured-post");
  const grid = document.getElementById("post-grid");
  const emptyState = document.getElementById("empty-state");
  const searchInput = document.getElementById("search-input");
  const tagFilter = document.getElementById("tag-filter");

  // Legacy masthead fields used only by the standalone blog/index.html page
  const issueCount = document.getElementById("issue-count");
  const mastheadDate = document.getElementById("masthead-date");
  const mastheadBand = document.getElementById("masthead-band");
  const categoryLine = document.getElementById("category-line");

  if (!grid) return;

  let posts = [];
  let activeTag = "all";
  let searchTerm = "";

  try {
    const res = await fetch(postsIndexPath);
    if (!res.ok) throw new Error("Failed to load posts-index.json");
    posts = await res.json();
  } catch (err) {
    grid.innerHTML = "";
    if (emptyState) {
      emptyState.hidden = false;
      emptyState.textContent =
        "Couldn't load posts. Run \"node build.js\" to generate posts-index.json.";
    }
    console.error(err);
    document.documentElement.classList.remove("hash-loading");
    return;
  }

  // posts-index.json is sorted newest-first by build.js — Issue No. is
  // oldest post = Issue No. 01, newest = Issue No. N — fixed per post
  // (not per position) so it stays stable as the reader searches/filters.
  const issueNumbers = new Map(posts.map((p, i) => [p.slug, posts.length - i]));
  const featured = posts[0];
  const rest = posts.slice(1);

  // Hero masthead meta line — today's date, post count, section count, price joke
  if (mastheadMeta) {
    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    });
    const sectionCount = new Set(posts.flatMap((p) => p.tags || [])).size;
    mastheadMeta.innerHTML = [
      today,
      `Vol. ${posts.length}`,
      `${sectionCount} Sections`,
      "Price: (1) Coffee",
    ].join(' <span class="meta-sep">&middot;</span> ');
  }

  // Legacy blog/index.html masthead — issue number, date, featured band, category line
  if (issueCount) {
    issueCount.textContent = posts.length;
  }
  if (mastheadDate && posts.length) {
    const d = new Date(posts[0].date + "T00:00:00");
    mastheadDate.textContent = isNaN(d)
      ? posts[0].date
      : d.toLocaleDateString("en-US", { month: "long", year: "numeric" });
  }
  if (mastheadBand && posts.length && posts[0].heroImage && posts[0].heroImage.src) {
    mastheadBand.style.backgroundImage = `url('${posts[0].heroImage.src}')`;
    mastheadBand.textContent = "";
    mastheadBand.setAttribute("aria-label", posts[0].heroImage.alt || "Featured post image");
  }
  if (categoryLine) {
    const allTags = Array.from(new Set(posts.flatMap((p) => p.tags || []))).sort();
    categoryLine.textContent = allTags.join("  |  ");
  }

  // Build circular tag filter buttons from every post's tags
  if (tagFilter) {
    const allTags = Array.from(new Set(posts.flatMap((p) => p.tags || []))).sort();
    allTags.forEach((tag) => {
      const btn = document.createElement("button");
      btn.className = "zine-tag-btn";
      btn.dataset.tag = tag;
      btn.innerHTML = `<span class="zine-tag-circle">${tag.charAt(0).toUpperCase()}</span><span class="zine-tag-label">${tag.toLowerCase()}</span>`;
      tagFilter.appendChild(btn);
    });

    tagFilter.addEventListener("click", (e) => {
      const btn = e.target.closest(".zine-tag-btn");
      if (!btn) return;
      activeTag = btn.dataset.tag;
      tagFilter
        .querySelectorAll(".zine-tag-btn")
        .forEach((b) => b.classList.toggle("is-active", b === btn));
      render();
    });
  }

  if (searchInput) {
    searchInput.addEventListener("input", (e) => {
      searchTerm = e.target.value.trim().toLowerCase();
      render();
    });
  }

  function matchesSearch(post) {
    if (!searchTerm) return true;
    const haystack = [post.title, post.excerpt, ...(post.tags || [])]
      .join(" ")
      .toLowerCase();
    return haystack.includes(searchTerm);
  }

  function matchesTag(post) {
    if (activeTag === "all") return true;
    return (post.tags || []).includes(activeTag);
  }

  function formatDate(dateStr) {
    const d = new Date(dateStr + "T00:00:00");
    if (isNaN(d)) return dateStr;
    return d.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  }

  function issueLabel(post) {
    return `Issue No. ${String(issueNumbers.get(post.slug)).padStart(2, "0")}`;
  }

  function featureHtml(post) {
    const imgTag = post.heroImage && post.heroImage.src
      ? `<img src="${post.heroImage.src}" alt="${post.heroImage.alt || ""}">`
      : `<div class="img-placeholder" role="img" aria-label="Post image placeholder">Image</div>`;

    const tags = (post.tags || [])
      .map((t) => `<li class="tag">${t}</li>`)
      .join("");

    return `
      <article class="zine-feature">
        <div class="zine-feature-media">${imgTag}</div>
        <div class="zine-feature-body">
          <p class="zine-byline">${issueLabel(post)}</p>
          <h3 class="zine-feature-title"><a href="${postLinkPrefix}${post.slug}.html">${post.title}</a></h3>
          <p class="zine-series"> ${post.series ? post.series.title : ""} ${post.series ? `Part ${post.series.part}` : ""}</p>
          <p class="zine-feature-excerpt">${post.excerpt}</p>
          <ul class="tag-list">${tags}</ul>
          <div class="zine-feature-meta">
            <span>${formatDate(post.date)}</span>
            <a class="zine-feature-link" href="${postLinkPrefix}${post.slug}.html">Read the post &rarr;</a>
          </div>
        </div>
      </article>`;
  }

  function cardHtml(post) {
    const imgTag = post.heroImage && post.heroImage.src
      ? `<img src="${post.heroImage.src}" alt="${post.heroImage.alt || ""}">`
      : `<div class="img-placeholder" role="img" aria-label="Post image placeholder">Image</div>`;

    const tags = (post.tags || [])
      .map((t) => `<li class="tag">${t}</li>`)
      .join("");

    return `
      <article class="zine-card">
        ${imgTag}
        <p class="zine-byline">${issueLabel(post)}</p>
        <h3><a href="${postLinkPrefix}${post.slug}.html">${post.title}</a></h3>
        <p class="zine-series"> ${post.series ? post.series.title : ""} ${post.series ? `Part ${post.series.part}` : ""}</p>
        <p>${post.excerpt}</p>
        <ul class="tag-list">${tags}</ul>
        <p class="slide-meta" style="margin-top:10px;">${formatDate(post.date)}</p>

      </article>`;
  }

  function render() {
    const filtered = rest.filter((p) => matchesSearch(p) && matchesTag(p));
    grid.innerHTML = filtered.length
      ? `<div class="zine-grid">${filtered.map(cardHtml).join("")}</div>`
      : "";
    if (emptyState) {
      emptyState.hidden = filtered.length > 0;
      emptyState.textContent = "No posts match your search or filter.";
    }
    // The homepage grid is its own scrollable panel (see .zine-grid-scroll) —
    // switching tags/search shouldn't leave it mid-scroll from the last filter.
    grid.scrollTop = 0;
  }

  // Landing here with a URL hash (e.g. a post page's "../index.html#contact"
  // link) scrolls the browser to that section before this script has
  // finished fetching and inserting the featured post + grid. That insert
  // pushes everything below #blog further down the page, so the browser's
  // own one-time scroll lands short — usually stalled right at the hero,
  // since the page's smooth-scroll CSS animates that first attempt and a
  // second smooth scroll fired mid-flight/mid-layout-shift doesn't reliably
  // finish. Force this corrective jump to be instant so it can't fight (or
  // get interrupted by) that in-flight animation — the page stays hidden
  // (see index.html's inline guard script) the whole time, so the reader
  // never sees the hero before landing on the right section. Reveal the
  // page only once this jump (or the decision not to make one) is done.
  function correctHashScroll() {
    if (location.hash) {
      const target = document.getElementById(location.hash.slice(1));
      if (target) {
        const html = document.documentElement;
        const prevBehavior = html.style.scrollBehavior;
        html.style.scrollBehavior = "auto";
        target.scrollIntoView();
        html.style.scrollBehavior = prevBehavior;
      }
    }
    document.documentElement.classList.remove("hash-loading");
  }

  if (featured && featuredContainer) {
    featuredContainer.innerHTML = featureHtml(featured);
  }

  if (!featured) {
    grid.innerHTML = "";
    if (emptyState) {
      emptyState.hidden = false;
      emptyState.textContent = "No posts yet — add one to /posts and run \"node build.js\".";
    }
    correctHashScroll();
    return;
  }

  render();
  correctHashScroll();
});
