// orbit-page.js
// -------------------------------------------------
// Drives orbit/index.html: renders the project grid from
// projects-index.json (generated by build.js from /projects/*.json).
// -------------------------------------------------

document.addEventListener("DOMContentLoaded", async () => {
  const grid = document.getElementById("project-grid");
  const emptyState = document.getElementById("project-empty");
  if (!grid) return;

  let projects = [];
  try {
    const res = await fetch("../projects-index.json");
    if (!res.ok) throw new Error("Failed to load projects-index.json");
    projects = await res.json();
  } catch (err) {
    console.error(err);
    if (emptyState) {
      emptyState.hidden = false;
      emptyState.textContent = 'Couldn\'t load projects. Run "node build.js" to generate projects-index.json.';
    }
    return;
  }

  if (projects.length === 0) {
    if (emptyState) {
      emptyState.hidden = false;
      emptyState.textContent = "No projects yet — add one to /projects and run \"node build.js\".";
    }
    return;
  }

  function projectCardHtml(project) {
    const href = `${project.slug}.html`;
    const mediaStyle = project.heroImage && project.heroImage.src
      ? ` style="background-image:url('${project.heroImage.src}')"`
      : "";
    const tags = (project.tags || []).map((t) => `<span class="tag">${t}</span>`).join("");

    return `
      <article class="project-card fade-section">
        <div class="project-card-media"${mediaStyle}></div>
        <div class="project-card-body">
          <p class="project-card-status">${project.status || ""}</p>
          <h3 class="project-card-title"><a href="${href}">${project.title}</a></h3>
          <p class="project-card-tagline">${project.tagline}</p>
          <div class="project-tags">${tags}</div>
          <a class="project-card-link" href="${href}">View Project &rarr;</a>
        </div>
      </article>`;
  }

  grid.innerHTML = projects.map(projectCardHtml).join("");
  if (window.observeFadeIns) window.observeFadeIns(grid);
});
