// script.js
// Home page carousel — pulls the 5 most recent posts from posts-index.json
// (generated by build.js) and renders them as slides.

document.addEventListener("DOMContentLoaded", async () => {
  const track = document.getElementById("carousel-track");
  const dotsContainer = document.querySelector(".carousel-dots");
  const prevBtn = document.querySelector(".carousel-prev");
  const nextBtn = document.querySelector(".carousel-next");

  if (!track) return;

  let posts = [];

  try {
    const res = await fetch("posts-index.json");
    if (!res.ok) throw new Error("Failed to load posts-index.json");
    posts = await res.json();
  } catch (err) {
    track.innerHTML = `<p style="padding:28px;">Couldn't load recent posts. Run "node build.js" to generate posts-index.json.</p>`;
    console.error(err);
    return;
  }

  // Homepage masthead meta line — today's date, post count, section count, price joke
  const mastheadMeta = document.getElementById("masthead-meta");
  if (mastheadMeta) {
    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    });
    const sectionCount = new Set(posts.flatMap((p) => p.tags || [])).size;
    mastheadMeta.innerHTML = [
      today,
      `Vol. ${posts.length}`,
      `${sectionCount} Sections`,
      "Price: One Coffee",
    ].join(' <span class="meta-sep">&middot;</span> ');
  }

  // posts-index.json is already sorted newest-first by build.js
  const recent = posts.slice(0, 5);

  if (recent.length === 0) {
    track.innerHTML = `<p style="padding:28px;">No posts yet — add one to /posts and run "node build.js".</p>`;
    return;
  }

  function formatDate(dateStr) {
    const d = new Date(dateStr + "T00:00:00");
    if (isNaN(d)) return dateStr;
    return d.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  }

  function slideHtml(post, index) {
    const imgTag = post.heroImage && post.heroImage.src
      ? `<img src="${post.heroImage.src}" alt="${post.heroImage.alt || ""}">`
      : `<div class="img-placeholder" role="img" aria-label="Post image placeholder">Image</div>`;

    const tags = (post.tags || [])
      .map((t) => `<li class="tag">${t}</li>`)
      .join("");

    return `
      <article class="carousel-slide${index === 0 ? " is-active" : ""}">
        ${imgTag}
        <div>
          <p class="slide-meta">Posted ${formatDate(post.date)}</p>
          <h3 class="slide-title"><a href="blog/${post.slug}.html">${post.title}</a></h3>
          <p class="slide-excerpt">${post.excerpt}</p>
          <ul class="tag-list">${tags}</ul>
        </div>
      </article>`;
  }

  track.innerHTML = recent.map(slideHtml).join("");

  const slides = Array.from(document.querySelectorAll(".carousel-slide"));
  let current = 0;

  slides.forEach((_, i) => {
    const dot = document.createElement("button");
    dot.className = "carousel-dot" + (i === 0 ? " is-active" : "");
    dot.setAttribute("aria-label", "Go to slide " + (i + 1));
    dot.addEventListener("click", () => goTo(i));
    dotsContainer.appendChild(dot);
  });

  const dots = Array.from(document.querySelectorAll(".carousel-dot"));

  function goTo(index) {
    slides[current].classList.remove("is-active");
    dots[current].classList.remove("is-active");
    current = (index + slides.length) % slides.length;
    slides[current].classList.add("is-active");
    dots[current].classList.add("is-active");
  }

  prevBtn.addEventListener("click", () => goTo(current - 1));
  nextBtn.addEventListener("click", () => goTo(current + 1));
});
