// ===========================================================================
// ENGINE (pure, no DOM dependency)
// ===========================================================================

// CUNTSCORES (skill -> stat weights) and CHALLENGE_CATEGORIES (challenge ->
// skill weights) come from DRAGG_DATA (dragg_data.js), generated by build.js
// from the sheet's CUNTScores and Challenge Categories tabs -- see build.js
// for the update workflow (drop fresh CSV exports in sheet-data/, run
// `node build.js`). Never hand-edit these; they're overwritten every build.
const CUNTSCORES = DRAGG_DATA.cuntScores;
const CHALLENGE_CATEGORIES = DRAGG_DATA.challengeCategories;
const EPISODE_CATEGORIES = DRAGG_DATA.episodeCategories || {};

// Widened from 7 to match the CUNTScores placement scale moving from a
// 5-point spread (BTM/ELIM=1..WIN=5) to a 10-point one (BTM/ELIM=1..WIN=10).
// Stats are a weighted average of placement points, and challenge scores
// are a linear function of stats, so the whole roster's skill-based score
// spread grows by exactly the same factor as the placement scale's slope
// (old->new maps 1->1 and 5->10, i.e. 2.25x) -- 7 * 2.25 = 15.75, rounded
// to 16 -- to keep the same skill-vs-luck balance the sim had before.
const RANDOMNESS_RANGE = 16;
const LIP_SYNC_TEMPERATURE = 1.0;

function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function skillScore(c, skill) {
  const w = CUNTSCORES[skill];
  return c.charisma * w.charisma + c.uniqueness * w.uniqueness + c.nerve * w.nerve + c.talent * w.talent;
}

function challengeScore(c, category, rng) {
  const weights = CHALLENGE_CATEGORIES[category].weights;
  let base = 0;
  for (const skill in weights) base += (weights[skill] / 10) * skillScore(c, skill);
  return base + (rng() * 2 - 1) * RANDOMNESS_RANGE;
}

function rankByChallenge(cast, category, rng) {
  const scored = cast.map((c) => [c, challengeScore(c, category, rng)]);
  scored.sort((a, b) => (b[1] - a[1]) || (skillScore(b[0], 'runway') - skillScore(a[0], 'runway')));
  return scored;
}

function lipSyncStrength(c) { return 0.5 * c.nerve + 0.5 * c.talent; }

function lipSyncWinProbabilities(cast, temperature) {
  const strengths = {}; cast.forEach((c) => { strengths[c.id] = lipSyncStrength(c); });
  const expVals = {}; let total = 0;
  cast.forEach((c) => { const v = Math.exp(strengths[c.id] / temperature); expVals[c.id] = v; total += v; });
  const probs = {}; cast.forEach((c) => { probs[c.id] = expVals[c.id] / total; });
  return probs;
}

function weightedPick(ids, weights, rng) {
  const total = weights.reduce((a, b) => a + b, 0);
  let r = rng() * total;
  for (let i = 0; i < ids.length; i++) { r -= weights[i]; if (r <= 0) return ids[i]; }
  return ids[ids.length - 1];
}

// Random challenge-category pick, weighted by each category's PROBABILITY
// (Challenge_Categories.csv) instead of a flat uniform chance across every
// category -- so a 0%-probability row (reserved for twists/finales, e.g.
// Talent Show) never gets drawn, and a category that's really a named slice
// of a bigger challenge (e.g. Rusical - Lip Sync vs. Rusical - Live) is
// drawn at its already-split share instead of as if it were a whole
// category on its own. Falls back to a plain uniform pick if every
// candidate's probability comes back 0 (an older sheet export with no
// PROBABILITY column), so this never regresses to always picking the same
// category.
function pickRandomCategory(candidates, rng) {
  const weights = candidates.map((cat) => CHALLENGE_CATEGORIES[cat].probability || 0);
  if (!weights.some((w) => w > 0)) return candidates[Math.floor(rng() * candidates.length)];
  return weightedPick(candidates, weights, rng);
}

// Placeholder Work Structure / Judging Structure weight tables for Custom
// mode (item 13). These are deliberately rough starting points, not tuned
// numbers -- Roberto's real per-episode Episode_Categories.csv data (the
// ChallengeMode/Num/JudgingMode columns) anchors the categories that
// actually happened in S5/S6; everything else is a same-family guess meant
// to be adjusted once he sees how a season plays out.
//
// work: relative weights across 'individual' / 'pairs' / 'groups' /
// 'twoTeams'. groupSize: the target size per group when work resolves to
// 'groups' (pairs is always size 2; twoTeams is always exactly 2 groups
// regardless of this number) -- the actual number of groups is worked out
// from however many queens are left that episode, not a fixed headcount
// (see computeNumGroups). judging: relative weights across 'individual' /
// 'blended' / 'uniform', only ever consulted when work !== 'individual'.
const TEAM_PROFILE_SOLO_ONLY = {
  work: { individual: 1, pairs: 0, groups: 0, twoTeams: 0 },
  groupSize: null,
  judging: { individual: 1, blended: 0, uniform: 0 },
};
const TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL = {
  work: { individual: 0, pairs: 0.15, groups: 0.85, twoTeams: 0 },
  groupSize: 3,
  judging: { individual: 0.75, blended: 0.25, uniform: 0 },
};
const TEAM_PROFILE_ACTING = {
  work: { individual: 0, pairs: 0, groups: 1, twoTeams: 0 },
  groupSize: 3,
  judging: { individual: 0.45, blended: 0.55, uniform: 0 },
};
const TEAM_PROFILE_ADVERT = {
  work: { individual: 0.55, pairs: 0.45, groups: 0, twoTeams: 0 },
  groupSize: 2,
  judging: { individual: 0, blended: 0, uniform: 1 },
};
// Rumix, Roast + Rumix, and Make Over + Girl Groups have no real S5/S6 data
// point at all (Rumix in particular can swing from solo to small groups to
// two full rival teams depending on the season, per Roberto), so they're
// placeholdered onto the same "mostly groups, mostly individually judged"
// profile as everything else pending his own numbers.
const CUSTOM_TEAM_PROFILES = {
  ball_classic: TEAM_PROFILE_SOLO_ONLY,
  ball_modern: TEAM_PROFILE_SOLO_ONLY,
  design: TEAM_PROFILE_SOLO_ONLY,
  design_rooms: TEAM_PROFILE_SOLO_ONLY,
  lip_sync: TEAM_PROFILE_SOLO_ONLY,
  make_over: TEAM_PROFILE_SOLO_ONLY,
  music_video: TEAM_PROFILE_SOLO_ONLY, // moot -- always hardcoded, never consults this table
  photo_shoot: TEAM_PROFILE_SOLO_ONLY,
  roast: TEAM_PROFILE_SOLO_ONLY,
  runway: TEAM_PROFILE_SOLO_ONLY,
  runway_design: TEAM_PROFILE_SOLO_ONLY,
  snatch_game: TEAM_PROFILE_SOLO_ONLY,
  stand_up: TEAM_PROFILE_SOLO_ONLY,
  talk_show: TEAM_PROFILE_SOLO_ONLY,
  talent_show: TEAM_PROFILE_SOLO_ONLY, // moot -- 0% probability, twist/finale-only

  choreo: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  girl_groups: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  improv: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  make_over_girl_groups: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  roast_rumix: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  rumix: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  rusical_lip_sync: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  rusical_live: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,
  rusical_rumix: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL, // moot -- 0% probability, twist/finale-only
  singing: TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL,

  acting: TEAM_PROFILE_ACTING,
  advert: TEAM_PROFILE_ADVERT,
};
const DEFAULT_TEAM_PROFILE = TEAM_PROFILE_GROUPS_MOSTLY_INDIVIDUAL;

// How much a team's average score counts toward each member's own result
// under Blended judging -- also a placeholder pending Roberto's tuning.
const TEAM_BLEND_WEIGHT = 0.5;

function pickWorkAndJudgingStructure(category, castSize, rng) {
  const profile = CUSTOM_TEAM_PROFILES[category] || DEFAULT_TEAM_PROFILE;
  const workKeys = Object.keys(profile.work);
  const work = weightedPick(workKeys, workKeys.map((k) => profile.work[k]), rng);
  if (work === 'individual') return { work: 'individual', groupSize: null, judging: 'individual' };
  const judgingKeys = Object.keys(profile.judging);
  const judging = weightedPick(judgingKeys, judgingKeys.map((k) => profile.judging[k]), rng);
  const groupSize = work === 'pairs' ? 2 : (work === 'twoTeams' ? Math.ceil(castSize / 2) : profile.groupSize);
  return { work, groupSize, judging };
}

// Turns a target group size into an actual number of groups for however
// many queens are left this episode -- "desired number of groups" rather
// than a fixed team size, so an odd remainder becomes one slightly bigger
// group instead of always stranding a lone single (see the item 13 design
// discussion). Two Rival Teams is always exactly 2 groups by definition.
function computeNumGroups(work, groupSize, castSize) {
  if (work === 'twoTeams') return 2;
  if (work === 'pairs') return Math.max(2, Math.round(castSize / 2));
  return Math.max(2, Math.round(castSize / groupSize));
}

// Builds, once per Replica-mode run, a remaining-cast-size -> queue-of-
// categories lookup from the season's real episode order
// (DRAGG_DATA.episodeCategories), so a "regular" episode looks up its
// category by how many queens are left instead of by raw episode number --
// keeping a specific real challenge (e.g. "the Ball") pinned to its real
// competitive milestone even if this Replica season's twist settings get
// changed away from the historical defaults. The premiere episode(s) and
// the trailing Music Video milestone + Final rows are always handled by
// their own hardcoded logic elsewhere in runSeason, so only the middle
// stretch feeds this queue.
//
// A single remaining-count can legitimately hold more than one real
// episode -- a Double Save leaves the headcount unchanged for a turn -- so
// each count maps to a queue of categories consumed in broadcast order, not
// a single value. A run whose twist settings drift from history far enough
// to exhaust a queue just falls back to the normal weighted-random pick
// (see pickReplicaCategory).
function buildReplicaCategoryQueue(season, castSize, twistConfig, premiereEpisodes) {
  const rows = EPISODE_CATEGORIES[season];
  if (!rows || rows.length <= premiereEpisodes + 2) return {};
  const middle = rows.slice(premiereEpisodes, rows.length - 2);
  const queue = {};
  let remaining = castSize - premiereEpisodes;
  middle.forEach((row) => {
    (queue[remaining] = queue[remaining] || []).push({
      category: row.category,
      work: row.work || 'individual',
      groupSize: row.groupSize || null,
      judging: row.judging || 'individual',
    });
    const de = twistConfig.doubleElimination;
    const ds = twistConfig.doubleSave;
    let delta = 1;
    if (de.on && de.fireMode === 'forced' && de.episode === row.ep) delta = 2;
    else if (ds.on && ds.fireMode === 'forced' && ds.episode === row.ep) delta = 0;
    remaining -= delta;
  });
  return queue;
}

// Custom mode's random category pick, bundled with a Work/Judging Structure
// roll (item 13) for whatever category comes back -- used both for Custom
// mode itself and as the fallback for any Replica episode the real-episode
// queue below has nothing left for.
function pickCustomEpisodeSpec(allCategories, castSize, rng) {
  const category = pickRandomCategory(allCategories, rng);
  const { work, groupSize, judging } = pickWorkAndJudgingStructure(category, castSize, rng);
  return { category, work, groupSize, judging };
}

function pickReplicaEpisodeSpec(queue, remainingCount, allCategories, rng) {
  const q = queue[remainingCount];
  if (q && q.length) return q.shift();
  return pickCustomEpisodeSpec(allCategories, remainingCount, rng);
}

function resolveGroupLipSync(cast, eliminateCount, rng, temperature) {
  temperature = temperature || LIP_SYNC_TEMPERATURE;
  let pool = cast.slice();
  const eliminated = [];
  for (let i = 0; i < eliminateCount; i++) {
    const probs = lipSyncWinProbabilities(pool, temperature);
    const ids = pool.map((c) => c.id);
    const inverseWeights = ids.map((id) => 1.0 - probs[id]);
    const cutId = weightedPick(ids, inverseWeights, rng);
    const cut = pool.find((c) => c.id === cutId);
    eliminated.push(cut);
    pool = pool.filter((c) => c.id !== cutId);
  }
  return { survivors: pool, eliminated };
}

function shuffleIds(ids, rng) {
  const arr = ids.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Shuffles the pool and deals it round-robin into however many groups are
// requested, always adding to whichever group is currently smallest -- the
// same even-split approach Split Premiere already uses for its unassigned
// queens (see buildTwists below), generalized to any number of groups.
function assignToGroups(ids, numGroups, rng) {
  const groups = Array.from({ length: numGroups }, () => []);
  shuffleIds(ids, rng).forEach((id) => {
    const smallest = groups.reduce((a, b) => (a.length <= b.length ? a : b));
    smallest.push(id);
  });
  return groups;
}

function buildTwists(twistConfig, mode, castIds, rng) {
  const twists = [];
  if (twistConfig.immunity.on) twists.push({ type: 'immunity', activeThroughEpisode: twistConfig.immunity.endsAfterEpisode });

  if (twistConfig.split.on) {
    const numGroups = Math.max(2, twistConfig.split.groups || 2);
    const labels = ['A', 'B', 'C', 'D'].slice(0, numGroups);
    const groupAssignments = {};
    labels.forEach((label) => { groupAssignments[label] = []; });
    // The player can manually assign each queen to a premiere group from the
    // setup screen (state.twistConfig.split.manualGroups, id -> label); honor
    // those choices first. Anyone left unassigned -- including everyone, if
    // the player never opened the group picker or used "Randomly Select" --
    // is shuffled and dealt round-robin into whichever group is smallest, so
    // the season always has a complete, roughly-even split.
    const manual = twistConfig.split.manualGroups || {};
    const unassigned = [];
    castIds.forEach((id) => {
      const label = manual[id];
      if (label && groupAssignments[label]) groupAssignments[label].push(id);
      else unassigned.push(id);
    });
    shuffleIds(unassigned, rng).forEach((id) => {
      const smallest = labels.reduce((a, b) => (groupAssignments[a].length <= groupAssignments[b].length ? a : b));
      groupAssignments[smallest].push(id);
    });
    // Split Premiere always spans exactly one episode per group, at the very
    // start of the season -- there's no separate configurable "merge
    // episode" any more (it never reliably matched groupAssignments' actual
    // length, and a premiere twist merging back mid-season made no sense
    // anyway). The merge itself needs no explicit code: once every group
    // has had its one episode, runSeason's default castPool (everyone still
    // active) already IS the merged cast.
    twists.push({ type: 'split', groupAssignments });
  }

  if (twistConfig.doubleElimination.on) {
    twists.push({ type: 'lipSyncOverride', outcome: 'bothEliminated', occurrencesRemaining: twistConfig.doubleElimination.occurrences, fireMode: twistConfig.doubleElimination.fireMode, probability: (twistConfig.doubleElimination.probability || 15) / 100, forcedEpisode: twistConfig.doubleElimination.episode });
  }
  if (twistConfig.doubleSave.on) {
    twists.push({ type: 'lipSyncOverride', outcome: 'bothSurvive', occurrencesRemaining: twistConfig.doubleSave.occurrences, fireMode: twistConfig.doubleSave.fireMode, probability: (twistConfig.doubleSave.probability || 15) / 100, forcedEpisode: twistConfig.doubleSave.episode });
  }

  if (twistConfig.semifinal.on) twists.push({ type: 'semifinalFourWay', fired: false, firedEpisode: null });

  if (mode === 'replica5') {
    const showcase = { type: 'topNShowcase', finalistCount: 3, fired: false, firedEpisode: null };
    twists.push(showcase);
    twists.push({ type: 'finaleFormat', finalistCount: 3, requires: [showcase], fired: false });
  } else {
    twists.push({ type: 'finaleFormat', finalistCount: 3, requires: [], fired: false });
  }
  return twists;
}

function runSeason(cast, twistConfig, mode, seed) {
  const rng = mulberry32(seed);
  const contestantsById = {}; cast.forEach((c) => { contestantsById[c.id] = c; });
  const castIds = cast.map((c) => c.id);
  const twists = buildTwists(twistConfig, mode, castIds, rng);

  let activeCastIds = castIds.slice();
  let eliminatedIds = [];
  let immuneId = null;
  let episodeNumber = 0;
  const episodes = [];
  let winnerId = null;
  let runnerUpIds = [];
  const lastEpisodeScores = {}; // most recent challenge score per contestant, for the finale's placement call
  const seasonScores = {}; // every graded challenge score per contestant this season, for the finale's season-performance blend

  const categories = Object.keys(CHALLENGE_CATEGORIES);
  const split = twists.find((t) => t.type === 'split');
  const semifinal = twists.find((t) => t.type === 'semifinalFourWay');
  const showcase = twists.find((t) => t.type === 'topNShowcase');
  const finale = twists.find((t) => t.type === 'finaleFormat');
  const lipSyncTwists = twists.filter((t) => t.type === 'lipSyncOverride');
  const immunity = twists.find((t) => t.type === 'immunity');

  // Split Premiere always spans exactly one episode per group at the very
  // start of the season (see buildTwists); with it off, the premiere is a
  // single episode. Hoisted above the loop since it's invariant across
  // episodes and Replica mode's category queue needs it up front too.
  const premiereEpisodes = split ? Object.keys(split.groupAssignments).length : 1;
  const replicaSeason = mode === 'replica5' ? 5 : mode === 'replica6' ? 6 : null;
  const replicaQueue = replicaSeason
    ? buildReplicaCategoryQueue(replicaSeason, cast.length, twistConfig, premiereEpisodes)
    : null;

  const MAX_EPISODES = 40;
  while (activeCastIds.length > 1 && episodeNumber < MAX_EPISODES) {
    episodeNumber++;
    let castPool = activeCastIds.slice();

    if (split) {
      const groupLabels = Object.keys(split.groupAssignments);
      const idx = episodeNumber - 1;
      if (idx < groupLabels.length) {
        // Still within the premiere: this episode belongs to one group only.
        const label = groupLabels[idx];
        castPool = split.groupAssignments[label].filter((id) => !eliminatedIds.includes(id));
      }
      // Once every group has had its one episode (idx >= groupLabels.length),
      // castPool is left as the default activeCastIds.slice() from above --
      // i.e. everyone still active, across every group -- which is already
      // the merged cast, so no separate merge step is needed.
    }

    // While Split Premiere is still in its premiere phase, a single group's
    // castPool can coincidentally match the exact size the 4-way semifinal,
    // Top-N showcase, or finale look for (especially now that groups can be
    // sized manually) -- that's a coincidence of group size, not the real
    // milestone, so none of those special formats can fire until every group
    // has had its one premiere episode and the cast is back together.
    const inSplitPremierePhase = !!split && episodeNumber <= Object.keys(split.groupAssignments).length;
    const semifinalEligible = !inSplitPremierePhase && semifinal && !semifinal.fired && castPool.length === 4;
    const showcaseEligible = !inSplitPremierePhase && showcase && !showcase.fired && castPool.length === showcase.finalistCount;
    const finaleEligible = !inSplitPremierePhase && finale && !finale.fired && castPool.length === finale.finalistCount
      && finale.requires.every((t) => t.fired && t.firedEpisode !== null && t.firedEpisode < episodeNumber);

    let category, scores, episodeTeams = null;
    if (finaleEligible) {
      category = 'final';
      scores = {};
      castPool.forEach((id) => {
        const finalChallengeScore = lastEpisodeScores[id] ?? 0;
        const history = seasonScores[id] || [];
        // A finalist's placement is decided by how she did in the final
        // challenge AND how she performed across the whole season, not the
        // final challenge alone -- weighted 60% final challenge / 40% season
        // average of every graded challenge score she earned this season.
        const seasonAverage = history.length
          ? history.reduce((sum, s) => sum + s, 0) / history.length
          : finalChallengeScore;
        scores[id] = 0.6 * finalChallengeScore + 0.4 * seasonAverage;
      });
    } else {
      // Premiere is always a design/sewing challenge (real seasons 1-8;
      // season 9+ introduced other premiere formats, not modeled yet). With
      // Split Premiere on, every group's one episode is still "the
      // premiere" even though each group gets its own episode number, so
      // they all get the SAME forced category here too, instead of each
      // group rolling its own random challenge. Replica mode looks up its
      // real historical category, and its real Work/Judging Structure
      // (item 13), once past the premiere and milestones (see
      // buildReplicaCategoryQueue); Custom mode -- and any Replica episode
      // the queue has nothing left for -- draws a weighted-random one
      // instead. The premiere and the semifinal/showcase milestone are
      // always plain solo challenges.
      const episodeSpec = (semifinalEligible || showcaseEligible)
        ? { category: 'music_video', work: 'individual', groupSize: null, judging: 'individual' }
        : (episodeNumber <= premiereEpisodes
          ? { category: 'design', work: 'individual', groupSize: null, judging: 'individual' }
          : (replicaQueue
            ? pickReplicaEpisodeSpec(replicaQueue, castPool.length, categories, rng)
            : pickCustomEpisodeSpec(categories, castPool.length, rng)));
      category = episodeSpec.category;
      const castObjs = castPool.map((id) => contestantsById[id]);
      const ranked = rankByChallenge(castObjs, category, rng);
      scores = {}; ranked.forEach(([c, s]) => { scores[c.id] = s; });

      // Work Structure / Judging Structure (item 13): everyone still earns
      // their own raw individual score above -- that's exactly what an
      // Individual-judged episode (solo or otherwise) uses as-is -- but a
      // team-worked episode judged as Blended or Uniform folds team
      // performance into it before it becomes her result for the episode
      // and her season history. Blended nudges her own score toward her
      // team's average; Uniform replaces it outright so the whole team
      // shares one outcome. (A team that's judged Individual despite
      // working together -- e.g. a Rusical critiqued one queen at a time --
      // is recorded for display but has no scoring effect.)
      if (episodeSpec.work !== 'individual') {
        const numGroups = computeNumGroups(episodeSpec.work, episodeSpec.groupSize, castPool.length);
        episodeTeams = assignToGroups(castPool, numGroups, rng);
        if (episodeSpec.judging !== 'individual') {
          const teamAverage = new Map();
          episodeTeams.forEach((team) => {
            const avg = team.reduce((sum, id) => sum + scores[id], 0) / team.length;
            team.forEach((id) => teamAverage.set(id, avg));
          });
          if (episodeSpec.judging === 'uniform') {
            castPool.forEach((id) => { scores[id] = teamAverage.get(id); });
          } else if (episodeSpec.judging === 'blended') {
            castPool.forEach((id) => {
              scores[id] = TEAM_BLEND_WEIGHT * teamAverage.get(id) + (1 - TEAM_BLEND_WEIGHT) * scores[id];
            });
          }
        }
      }

      castPool.forEach((id) => {
        lastEpisodeScores[id] = scores[id];
        (seasonScores[id] = seasonScores[id] || []).push(scores[id]);
      });
    }

    const labels = {};
    let eliminatedThisEpisode = [];
    let bottomTwo = [];
    const suppressNormal = semifinalEligible || showcaseEligible || finaleEligible;

    if (suppressNormal) {
      if (semifinalEligible) {
        const castObjs = castPool.map((id) => contestantsById[id]);
        const { survivors, eliminated } = resolveGroupLipSync(castObjs, 1, rng);
        survivors.forEach((c) => { labels[c.id] = 'PASS'; });
        labels[eliminated[0].id] = 'ELIM';
        eliminatedThisEpisode = [eliminated[0].id];
        semifinal.fired = true; semifinal.firedEpisode = episodeNumber;
      } else if (showcaseEligible) {
        castPool.forEach((id) => { labels[id] = 'PASS'; });
        showcase.fired = true; showcase.firedEpisode = episodeNumber;
      } else if (finaleEligible) {
        const rankedIds = castPool.slice().sort((a, b) => scores[b] - scores[a]);
        winnerId = rankedIds[0];
        runnerUpIds = rankedIds.slice(1);
        labels[winnerId] = 'WIN!';
        runnerUpIds.forEach((id) => { labels[id] = 'RU'; });
        eliminatedThisEpisode = runnerUpIds.slice();
        finale.fired = true; finale.firedEpisode = episodeNumber;
      }
    } else {
      const rankedIds = castPool.slice().sort((a, b) => scores[b] - scores[a]);
      const n = rankedIds.length;
      const winner = rankedIds[0];
      const riskPool = rankedIds.slice(1);
      const atRisk = riskPool.filter((id) => id !== immuneId);
      bottomTwo = atRisk.length >= 2 ? atRisk.slice(-2) : atRisk;

      rankedIds.forEach((id) => {
        if (id === winner) labels[id] = 'WIN';
        else if (bottomTwo.includes(id)) labels[id] = 'BTM';
        else labels[id] = 'SAFE';
      });

      if (n >= 5) {
        const rest = rankedIds.filter((id) => labels[id] === 'SAFE');
        const topCount = Math.min(2, rest.length);
        for (let i = 0; i < topCount; i++) labels[rest[i]] = 'TOP';
        const lowCandidates = rest.slice(topCount).filter((id) => id !== immuneId);
        if (lowCandidates.length) labels[lowCandidates[lowCandidates.length - 1]] = 'LOW';
      }

      const eligibleLipSyncTwists = lipSyncTwists.filter((t) => {
        if (t.occurrencesRemaining <= 0 || bottomTwo.length !== 2) return false;
        return t.fireMode === 'forced' ? t.forcedEpisode === episodeNumber : true;
      });
      const episodesRemaining = Math.max(1, activeCastIds.length - 2);
      // A twist can also fire because the bottom two just gave an unusually
      // strong ("amazing," for Double Save) or unusually weak ("horrible,"
      // for Double Elimination) lip sync performance relative to who's
      // still in the competition -- top/bottom third of the remaining
      // cast's lip sync strength. This is an extra path OR'd onto the
      // twist's own probability/occurrence math, never a replacement for
      // it, and it's skipped for a forced-mode twist, which fires on its
      // scheduled episode regardless of performance.
      const remainingStrengths = castPool
        .map((id) => lipSyncStrength(contestantsById[id]))
        .sort((a, b) => a - b);
      const thirdSize = Math.max(1, Math.floor(remainingStrengths.length / 3));
      const topThirdCutoff = remainingStrengths[remainingStrengths.length - thirdSize];
      const bottomThirdCutoff = remainingStrengths[thirdSize - 1];
      const bottomTwoStrengths = bottomTwo.map((id) => lipSyncStrength(contestantsById[id]));
      const performanceMatches = (outcome) => {
        if (outcome === 'bothSurvive') return bottomTwoStrengths.every((s) => s >= topThirdCutoff);
        if (outcome === 'bothEliminated') return bottomTwoStrengths.every((s) => s <= bottomThirdCutoff);
        return false;
      };
      let firing = null;
      for (const t of eligibleLipSyncTwists) {
        let should;
        if (t.fireMode === 'forced') should = true;
        else if (t.fireMode === 'custom') should = performanceMatches(t.outcome) || rng() < t.probability;
        else should = performanceMatches(t.outcome) || rng() < Math.min(1, t.occurrencesRemaining / episodesRemaining);
        if (should) { firing = t; break; }
      }

      if (firing) {
        if (firing.outcome === 'bothEliminated') {
          eliminatedThisEpisode = bottomTwo.slice();
          bottomTwo.forEach((id) => { labels[id] = 'ELIM'; });
        }
        firing.occurrencesRemaining -= 1;
      } else if (bottomTwo.length === 2) {
        const bottomObjs = bottomTwo.map((id) => contestantsById[id]);
        const { survivors, eliminated } = resolveGroupLipSync(bottomObjs, 1, rng);
        labels[eliminated[0].id] = 'ELIM';
        eliminatedThisEpisode = [eliminated[0].id];
      }

      if (immunity) immuneId = episodeNumber <= immunity.activeThroughEpisode ? winner : null;
    }

    episodes.push({
      number: episodeNumber,
      category,
      castPool: castPool.slice(),
      labels: { ...labels },
      eliminated: eliminatedThisEpisode.slice(),
      teams: episodeTeams ? episodeTeams.map((team) => team.slice()) : null,
    });
    eliminatedIds = eliminatedIds.concat(eliminatedThisEpisode);
    activeCastIds = activeCastIds.filter((id) => !eliminatedThisEpisode.includes(id));

    if (finaleEligible) break;
  }

  return { episodes, winnerId, runnerUpIds };
}

// ===========================================================================
// DATA
// ===========================================================================

// Roster is generated from DRAGG_DATA (dragg_data.js), which mirrors
// dragg_data.json -- both produced by build.js from CSV exports of the
// "Drag Race: The Simulator" Google Sheet's Main Page tab. To refresh:
// export a fresh Main_Page.csv into sheet-data/ and run `node build.js`
// (see the comment at the top of build.js). Never hand-edit these arrays
// directly -- they're overwritten every build.
//
// A queen can have more than one "version" -- e.g. a Season 5 debut and a
// later All Stars 2 run -- each with its own Charisma/Uniqueness/Nerve/Talent
// stats. ALL_QUEENS has ONE entry per queen (per QID); qn.versions holds all
// of her appearances, and qn.season/c/u/n/t always mirror whichever version
// is currently active (qn.activeVersionIdx). setActiveVersion() is the only
// thing that should change which version is active -- everything else in
// this file just reads qn.season/c/u/n/t as if she only had one.
const ALL_QUEENS = DRAGG_DATA.queens.map((q) => {
  const versions = q.versions.map((v) => ({
    sid: v.sid,
    season: v.season,
    seasonLabel: v.seasonLabel,
    shortLabel: v.shortLabel,
    c: v.charisma,
    u: v.uniqueness,
    n: v.nerve,
    t: v.talent,
  }));
  // Default active version = earliest (lowest) SID, i.e. her original/debut season.
  const activeVersionIdx = 0; // versions are already sorted ascending by SID in dragg_data.json
  const active = versions[activeVersionIdx];
  return {
    id: q.qid,
    name: q.name,
    hometown: DRAGG_DATA.countries[q.country] || q.country,
    country: q.country,
    versions,
    activeVersionIdx,
    season: active.season,
    seasonLabel: active.seasonLabel,
    shortLabel: active.shortLabel,
    c: active.c,
    u: active.u,
    n: active.n,
    t: active.t,
  };
});

// Mutates qn in place so qn.season/seasonLabel/shortLabel/c/u/n/t reflect
// qn.versions[idx]. This is the one place that changes a queen's "active"
// stats -- the roster card toggle and the Season filter both call it.
function setActiveVersion(qn, idx) {
  if (idx < 0 || idx >= qn.versions.length || idx === qn.activeVersionIdx) return;
  const v = qn.versions[idx];
  qn.activeVersionIdx = idx;
  qn.season = v.season;
  qn.seasonLabel = v.seasonLabel;
  qn.shortLabel = v.shortLabel;
  qn.c = v.c;
  qn.u = v.u;
  qn.n = v.n;
  qn.t = v.t;
}

// Fixed index into ALL_QUEENS drives a queen's palette slot (avatarClass) --
// resolved once so a queen's color stays stable regardless of how the
// roster is filtered/sorted, and so card/chip/badge/banner all agree.
const AVATAR_INDEX_BY_ID = {};
ALL_QUEENS.forEach((q, i) => { AVATAR_INDEX_BY_ID[q.id] = i; });

function avatarClass(index) { return `avatar-${((index % 6) + 6) % 6}`; }
function initialsOf(name) { return name.split(' ').map((p) => p[0]).join(''); }

function categoryLabel(cat) {
  if (cat === 'final') return 'Grand Finale';
  return (cat || '').split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

const REPLICA_PRESETS = {
  replica5: {
    castSize: 14,
    twistConfig: {
      immunity: { on: true, endsAfterEpisode: 4 },
      split: { on: false, groups: 2, manualGroups: {} },
      doubleElimination: { on: true, occurrences: 1, fireMode: 'forced', probability: 15, episode: 4 },
      doubleSave: { on: true, occurrences: 1, fireMode: 'forced', probability: 15, episode: 7 },
      semifinal: { on: false },
    },
  },
  replica6: {
    castSize: 14,
    twistConfig: {
      immunity: { on: false, endsAfterEpisode: 6 },
      split: { on: true, groups: 2, manualGroups: {} },
      doubleElimination: { on: false, occurrences: 1, fireMode: 'guaranteed', probability: 15, episode: 1 },
      doubleSave: { on: true, occurrences: 1, fireMode: 'forced', probability: 15, episode: 7 },
      semifinal: { on: true },
    },
  },
};

// ===========================================================================
// STATE
// ===========================================================================

const state = {
  query: '', selected: [], mode: 'custom', sortBy: 'alpha', filterCountry: 'all', filterSeason: 'all',
  customCastSize: 14, view: 'setup', simResult: null, lastCast: [],
  twistConfig: {
    immunity: { on: false, endsAfterEpisode: 6 },
    split: { on: false, groups: 2, manualGroups: {} },
    doubleElimination: { on: false, occurrences: 1, fireMode: 'guaranteed', probability: 15, episode: 1 },
    doubleSave: { on: false, occurrences: 1, fireMode: 'guaranteed', probability: 15, episode: 1 },
    semifinal: { on: false },
  },
  splitPicked: [],
  editingCastId: null,
};

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;'); }

function computeDerived() {
  const isReplicaMode = state.mode === 'replica5' || state.mode === 'replica6';
  const targetSize = isReplicaMode ? REPLICA_PRESETS[state.mode].castSize : (state.customCastSize || 0);
  const hasValidCastSize = targetSize > 0;
  const selectedCount = state.selected.length;
  const readyToContinue = hasValidCastSize && selectedCount === targetSize;
  const hasMismatch = !readyToContinue;
  const mismatchMessage = !hasValidCastSize ? 'Enter a cast size (8 or more).'
    : selectedCount < targetSize ? `Cast size not met — need ${targetSize - selectedCount} more.`
    : selectedCount > targetSize ? `Too many queens selected — remove ${selectedCount - targetSize}.`
    : '';
  return { isReplicaMode, targetSize, hasValidCastSize, selectedCount, readyToContinue, hasMismatch, mismatchMessage };
}

// ===========================================================================
// RENDER
//
// The HTML file owns the page shells (#page-setup / #page-results) and every
// element that is structurally always present -- the 3 mode buttons, the 5
// twist rows and their fields, the setup toolbar, the results header, the
// winner banner skeleton. Nothing here builds that chrome from a template
// string; it only toggles classes/attributes on it and fills the pieces
// whose length genuinely varies with data (the roster grid, cast chips,
// episode list, runner-up strip). Styling for all of it lives in styles.css
// -- this file sets state, not inline style strings.
// ===========================================================================

function setInputValue(el, val) {
  const str = val === undefined || val === null ? '' : String(val);
  if (el.value !== str) el.value = str;
}

function setFieldValue(key, field, value) {
  const el = document.querySelector(`[data-action="twistField"][data-key="${key}"][data-field="${field}"]`);
  if (el) setInputValue(el, value);
}

function rebuildWithScroll(el, html) {
  const pos = el.scrollLeft;
  el.innerHTML = html;
  el.scrollLeft = pos;
}

function buildQueenCardHTML(qn, isSelected) {
  const idx = AVATAR_INDEX_BY_ID[qn.id] ?? 0;
  const stats = [
    { letter: 'C', value: qn.c, cls: 'stat-c' },
    { letter: 'U', value: qn.u, cls: 'stat-u' },
    { letter: 'N', value: qn.n, cls: 'stat-n' },
    { letter: 'T', value: qn.t, cls: 'stat-t' },
  ];
  const statsHtml = stats.map((s) => `
    <div class="stat-row">
      <div class="stat-letter ${s.cls}">${s.letter}</div>
      <div class="stat-track"><div class="stat-fill ${s.cls}" style="width:${Math.min(100, s.value * 10)}%"></div></div>
      <div class="stat-value">${s.value.toFixed(1)}</div>
    </div>`).join('');
  // Multi-version queens (e.g. Alaska: S5 debut + All Stars 2) get a small
  // pill toggle so the player can pick which season's stats are active.
  // Single-version queens get nothing extra here.
  //
  // While the Season filter is set to a specific season, getFilteredQueens()
  // forces every matching queen onto that season's version on every render
  // -- so the toggle is effectively locked (clicking the other pill would
  // just snap back). Show that plainly: a lock icon + a yellow ring on the
  // pill the filter is holding in place, rather than letting it silently
  // ignore clicks.
  const seasonLocked = state.filterSeason !== 'all';
  const lockIconSvg = '<svg class="pill-lock-icon" width="9" height="9" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1a5 5 0 0 0-5 5v3H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-9a2 2 0 0 0-2-2h-1V6a5 5 0 0 0-5-5zm-3 8V6a3 3 0 0 1 6 0v3H9z"/></svg>';
  const versionToggleHtml = qn.versions.length > 1
    ? `<div class="version-toggle">${qn.versions.map((v, i) => {
        const isActive = i === qn.activeVersionIdx;
        const isLocked = isActive && seasonLocked;
        const cls = `version-pill${isActive ? ' active' : ''}${isLocked ? ' locked' : ''}`;
        const title = isLocked ? ` title="Locked to ${esc(v.seasonLabel)} by the Season filter"` : '';
        return `<button type="button" class="${cls}" data-action="setVersion" data-id="${qn.id}" data-vidx="${i}"${title}>${isLocked ? lockIconSvg : ''}${esc(v.shortLabel)}</button>`;
      }).join('')}</div>`
    : '';
  return `
    <div class="queen-card${isSelected ? ' selected' : ''}">
      <button class="queen-card-btn" data-action="toggleQueen" data-id="${qn.id}">
        <div class="queen-card-inner">
          <div class="queen-avatar-wrap avatar ${avatarClass(idx)}">
            <span class="display queen-initials">${esc(initialsOf(qn.name))}</span>
            <div class="queen-check"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#2E1A00" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg></div>
            <div class="queen-season-badge">${esc(qn.shortLabel)}</div>
          </div>
          <div class="queen-info">
            <div class="display queen-name">${esc(qn.name)}</div>
            <div class="queen-hometown">${esc(qn.hometown)}</div>
          </div>
          <div class="queen-stats">${statsHtml}</div>
        </div>
      </button>
      ${versionToggleHtml}
    </div>`;
}

// CUNT scores under each Current Cast card, colored to match the stat
// colors used on the full roster card (stat-c/u/n/t).
const CAST_STAT_DOT_STYLE = [
  { key: 'c', bg: '#D6006F', color: '#FFFFFF', label: 'Charisma' },
  { key: 'u', bg: '#6C2EB9', color: '#FFFFFF', label: 'Uniqueness' },
  { key: 'n', bg: '#D4AF37', color: '#2E1A00', label: 'Nerve' },
  { key: 't', bg: '#2E8B84', color: '#FFFFFF', label: 'Talent' },
];
function buildCastStatDotsHTML(qn) {
  return `<div class="cast-card-stats">${CAST_STAT_DOT_STYLE.map((s) => {
    const value = qn[s.key];
    return `<div class="cast-card-stat-dot" style="background:${s.bg};color:${s.color};" title="${s.label}: ${value.toFixed(1)}">${value.toFixed(1)}</div>`;
  }).join('')}</div>`;
}

// Quick-edit popover (lower-right pencil on the profile pic) -- for now just
// lets you switch which version of a multi-version queen is active without
// having to remove and re-add her.
function buildCastEditPopHTML(qn) {
  if (qn.versions.length <= 1) {
    return `<div class="cast-card-editpop">
      <div class="cast-card-editpop-label">Version</div>
      <div class="cast-card-editpop-empty">No other versions</div>
    </div>`;
  }
  const versionsHtml = qn.versions.map((v, i) => {
    const isActive = i === qn.activeVersionIdx;
    return `<button type="button" class="version-pill${isActive ? ' active' : ''}" data-action="setVersionAndClose" data-id="${qn.id}" data-vidx="${i}">${esc(v.shortLabel)}</button>`;
  }).join('');
  return `<div class="cast-card-editpop">
    <div class="cast-card-editpop-label">Version</div>
    <div class="cast-card-editpop-versions">${versionsHtml}</div>
  </div>`;
}

function buildCastCardHTML(qn) {
  const idx = AVATAR_INDEX_BY_ID[qn.id] ?? 0;
  const isEditing = state.editingCastId === qn.id;
  // Version is locked in the moment she's added to Current Cast -- the badge
  // shows whichever version was active when she was selected; the pencil
  // button opens a quick popover to change it (or other quick edits later)
  // without removing and re-adding her.
  return `<div class="cast-card${isEditing ? ' editing' : ''}">
    <div class="cast-card-avatar-wrap">
      <div class="display cast-card-avatar avatar ${avatarClass(idx)}">${esc(initialsOf(qn.name))}</div>
      <button data-action="removeQueen" data-id="${qn.id}" class="cast-card-remove" title="Remove from cast">
        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#F3E4EC" stroke-width="2.5" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
      </button>
      <div class="cast-card-version-badge">${esc(qn.shortLabel)}</div>
      <button data-action="toggleCastEdit" data-id="${qn.id}" class="cast-card-edit" title="Quick edit">
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#F3E4EC" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"></path><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"></path></svg>
      </button>
      ${isEditing ? buildCastEditPopHTML(qn) : ''}
    </div>
    <div class="cast-card-pill"><span class="cast-card-name">${esc(qn.name)}</span></div>
    ${buildCastStatDotsHTML(qn)}
  </div>`;
}

// Split Premiere group picker: lets the player manually decide which
// premiere episode (group) each selected queen goes into, instead of
// always leaving it to a random shuffle.
function buildSplitGroupChipHTML(qn, groupLabel, isPicked) {
  const idx = AVATAR_INDEX_BY_ID[qn.id] ?? 0;
  const cls = [groupLabel ? `assigned grp-${groupLabel.toLowerCase()}` : 'unassigned', isPicked ? 'picked' : '']
    .filter(Boolean).join(' ');
  return `<button type="button" class="split-chip ${cls}" data-action="toggleSplitPick" data-id="${qn.id}" title="Click to select">
    <div class="display chip-avatar avatar ${avatarClass(idx)}">${esc(initialsOf(qn.name))}</div>
    <span class="chip-name">${esc(qn.name)}</span>
  </button>`;
}

// Item 9: instead of clicking one queen at a time to cycle her through
// groups, select several queens (toggleSplitPick) then click a group to
// assign all of them at once (assignSplitGroup) -- or "Unassign".
function buildSplitGroupsToolbarHTML(numGroups, pickedCount) {
  const labels = ['A', 'B', 'C', 'D'].slice(0, numGroups);
  const disabledAttr = pickedCount === 0 ? 'disabled' : '';
  const groupButtons = labels.map((l) =>
    `<button type="button" class="btn-assign-group" data-action="assignSplitGroup" data-label="${l}" ${disabledAttr}>Move to Premiere ${l}</button>`
  ).join('');
  return `<div class="split-groups-toolbar">
    <span>${pickedCount ? `<span class="picked-count">${pickedCount}</span> selected` : 'Select queens below, then assign them to a group.'}</span>
    ${groupButtons}
    <button type="button" class="btn-assign-group" data-action="assignSplitGroup" data-label="" ${disabledAttr}>Unassign</button>
    ${pickedCount ? '<button type="button" class="btn-assign-group" data-action="clearSplitPick">Clear selection</button>' : ''}
  </div>`;
}

function buildSplitGroupsColumnsHTML(selectedQueens, splitTwist) {
  const numGroups = Math.max(2, splitTwist.groups || 2);
  const labels = ['A', 'B', 'C', 'D'].slice(0, numGroups);
  const manual = splitTwist.manualGroups || {};
  const pickedSet = new Set(state.splitPicked || []);
  const buckets = { UNASSIGNED: [] };
  labels.forEach((l) => { buckets[l] = []; });
  selectedQueens.forEach((qn) => {
    const label = manual[qn.id];
    if (label && buckets[label]) buckets[label].push(qn); else buckets.UNASSIGNED.push(qn);
  });
  const columnHtml = (key, title) => `
    <div class="split-group-column">
      <div class="split-group-header"><span>${esc(title)}</span><span class="split-group-count">${buckets[key].length}</span></div>
      <div class="split-group-chips">${buckets[key].map((qn) => buildSplitGroupChipHTML(qn, key === 'UNASSIGNED' ? null : key, pickedSet.has(qn.id))).join('') || '<div class="split-group-empty">Empty</div>'}</div>
    </div>`;
  return columnHtml('UNASSIGNED', 'Unassigned') + labels.map((l) => columnHtml(l, `Premiere ${l}`)).join('');
}

// Item 2: winner + top queens on the top row, safe queens in the middle,
// low/bottom/eliminated on the bottom row -- a more readable summary than a
// flat list of pills. RU (finale runner-up) reads as a top-tier result too,
// since she's a finalist, not a mid-pack "safe."
const RESULT_LABEL_PRIORITY = { WIN: 0, 'WIN!': 0, TOP: 1, RU: 1, SAFE: 0, PASS: 1, LOW: 0, BTM: 1, ELIM: 2 };
function resultTierFor(label) {
  if (label === 'WIN' || label === 'WIN!' || label === 'TOP' || label === 'RU') return 'top';
  if (label === 'LOW' || label === 'BTM' || label === 'ELIM') return 'low';
  return 'safe';
}
function resultPillClass(label) {
  switch (label) {
    case 'WIN': return 'res-win';
    case 'WIN!': return 'res-win-bang';
    case 'TOP': return 'res-top';
    case 'SAFE': return 'res-safe';
    case 'LOW': return 'res-low';
    case 'BTM': return 'res-btm';
    case 'ELIM': return 'res-elim';
    case 'PASS': return 'res-pass';
    case 'RU': return 'res-ru';
    default: return 'res-default';
  }
}
function buildResultCardHTML(id, label, namesById) {
  const name = namesById[id] || id;
  const idx = AVATAR_INDEX_BY_ID[id] ?? 0;
  return `<div class="result-card">
    <div class="display result-avatar avatar ${avatarClass(idx)}">${esc(initialsOf(name))}</div>
    <div class="result-pill ${resultPillClass(label)}">
      <span class="result-name">${esc(name)}</span>
      <span class="result-label">${esc(label)}</span>
    </div>
  </div>`;
}
function buildEpisodeHTML(ep, namesById) {
  const tiers = { top: [], safe: [], low: [] };
  ep.castPool.forEach((id) => { tiers[resultTierFor(ep.labels[id] || '')].push(id); });
  const byPriority = (a, b) => (RESULT_LABEL_PRIORITY[ep.labels[a]] ?? 9) - (RESULT_LABEL_PRIORITY[ep.labels[b]] ?? 9);
  tiers.top.sort(byPriority);
  tiers.safe.sort(byPriority);
  tiers.low.sort(byPriority);
  const tierRowHtml = (ids, tierLabel) => ids.length
    ? `<div class="result-tier"><div class="result-tier-label">${esc(tierLabel)}</div>${ids.map((id) => buildResultCardHTML(id, ep.labels[id] || '', namesById)).join('')}</div>`
    : '';
  const resultsHtml = tierRowHtml(tiers.top, 'Top')
    + tierRowHtml(tiers.safe, 'Safe')
    + tierRowHtml(tiers.low, 'Low / Bottom / Eliminated');
  const elimLine = ep.eliminated.length
    ? `<div class="elim-line">${ep.eliminated.map((id) => esc(namesById[id] || id)).join(' and ')} ${ep.eliminated.length > 1 ? 'are' : 'is'} eliminated.</div>` : '';
  return `<div class="episode-card">
    <div class="episode-header">
      <div class="display episode-number">Episode ${ep.number}</div>
      <div class="episode-category">${esc(categoryLabel(ep.category))}</div>
    </div>
    <div class="result-tiers">${resultsHtml}</div>
    ${elimLine}
  </div>`;
}

function initCountryOptions() {
  const countries = [...new Set(ALL_QUEENS.map((qn) => qn.country))].sort();
  const select = document.getElementById('country-select');
  countries.forEach((c) => {
    const opt = document.createElement('option');
    opt.value = c; opt.textContent = c;
    select.appendChild(opt);
  });
}

function initSeasonOptions() {
  // One option per distinct SID across every queen's versions (not just her
  // currently-active one) so a season only some queens have visited -- e.g.
  // All Stars 2 -- still shows up. Labeled by seasonLabel, not raw season
  // number, since season numbers repeat across versions (Season 2 vs All
  // Stars 2 are different SIDs).
  const bySid = new Map();
  ALL_QUEENS.forEach((qn) => {
    qn.versions.forEach((v) => { if (!bySid.has(v.sid)) bySid.set(v.sid, v.seasonLabel); });
  });
  const sids = [...bySid.keys()].sort();
  const select = document.getElementById('season-select');
  sids.forEach((sid) => {
    const opt = document.createElement('option');
    opt.value = sid; opt.textContent = bySid.get(sid);
    select.appendChild(opt);
  });
}

function getFilteredQueens() {
  const q = state.query.trim().toLowerCase();
  return ALL_QUEENS.filter((qn) => {
    if (q && !qn.name.toLowerCase().includes(q) && !qn.hometown.toLowerCase().includes(q)) return false;
    if (state.filterCountry !== 'all' && qn.country !== state.filterCountry) return false;
    if (state.filterSeason !== 'all') {
      const vIdx = qn.versions.findIndex((v) => v.sid === state.filterSeason);
      if (vIdx === -1) return false;
      // Filtering to a season drives which version of a multi-version queen
      // is shown/cast -- e.g. filtering to "All Stars 2" makes Alaska's card
      // (and Add All Shown) use her AS2 stats, not her Season 5 debut ones.
      setActiveVersion(qn, vIdx);
    }
    return true;
  });
}

function buildTrackRecordRows(sim, cast) {
  const rows = [];
  const seen = new Set();
  if (sim.winnerId) { rows.push(sim.winnerId); seen.add(sim.winnerId); }
  sim.runnerUpIds.forEach((id) => { if (!seen.has(id)) { rows.push(id); seen.add(id); } });
  for (let i = sim.episodes.length - 1; i >= 0; i--) {
    sim.episodes[i].eliminated.forEach((id) => { if (!seen.has(id)) { rows.push(id); seen.add(id); } });
  }
  cast.forEach((c) => { if (!seen.has(c.id)) { rows.push(c.id); seen.add(c.id); } });
  return rows;
}

function computeTrackPlacements(sim, cast) {
  // Standard competition ranking: everyone eliminated together in the
  // same episode -- including a double elimination -- ties for the same
  // placement, and whoever's next skips the numbers that tie consumed.
  const placements = {};
  const seen = new Set();
  let place = 1;
  const applyGroup = (ids) => {
    const fresh = ids.filter((id) => !seen.has(id));
    if (!fresh.length) return;
    fresh.forEach((id) => { placements[id] = place; seen.add(id); });
    place += fresh.length;
  };
  if (sim.winnerId) applyGroup([sim.winnerId]);
  applyGroup(sim.runnerUpIds);
  for (let i = sim.episodes.length - 1; i >= 0; i--) {
    applyGroup(sim.episodes[i].eliminated);
  }
  applyGroup(cast.map((c) => c.id));
  return placements;
}

function trackCellClass(label) {
  switch (label) {
    case 'WIN': return 'trk-win';
    case 'WIN!': return 'trk-pos-winner';
    case 'TOP': return 'trk-top';
    case 'SAFE': return 'trk-safe';
    case 'LOW': return 'trk-low';
    case 'BTM': return 'trk-btm';
    case 'ELIM': return 'trk-elim';
    case 'PASS': return 'trk-pass';
    case 'RU': return 'trk-pos-ru';
    default: return 'trk-blank';
  }
}

function ordinal(n) {
  const rem100 = n % 100;
  if (rem100 >= 11 && rem100 <= 13) return n + 'th';
  switch (n % 10) {
    case 1: return n + 'st';
    case 2: return n + 'nd';
    case 3: return n + 'rd';
    default: return n + 'th';
  }
}

function renderTrackRecord(sim, cast, namesById) {
  const head = document.getElementById('track-table-head');
  const body = document.getElementById('track-table-body');
  // Item 3: challenge category under Ep #, wrapped onto its own line.
  const episodeHeaders = sim.episodes.map((ep) => ({
    num: ep.category === 'final' ? 'Final' : ('Ep ' + ep.number),
    cat: categoryLabel(ep.category),
  }));
  head.innerHTML = '<tr><th class="track-name-col">Queen</th>'
    + episodeHeaders.map((h) => `<th><span class="ep-num">${esc(h.num)}</span><span class="ep-cat">${esc(h.cat)}</span></th>`).join('')
    + '</tr>';
  const rows = buildTrackRecordRows(sim, cast);
  const placements = computeTrackPlacements(sim, cast);
  body.innerHTML = rows.map((id) => {
    const name = namesById[id] || id;
    const idx = AVATAR_INDEX_BY_ID[id] ?? 0;
    const cells = sim.episodes.map((ep) => {
      if (!ep.castPool.includes(id)) return '<td class="trk-blank">&mdash;</td>';
      const label = ep.labels[id] || '';
      return `<td class="${trackCellClass(label)}">${esc(label)}</td>`;
    }).join('');
    // Item 5: Pos moves in front of the avatar/name and shrinks to a short,
    // color-keyed tag instead of spelled-out WINNER/RUNNER-UP text.
    // A double elimination (or any tie) shares one placement number,
    // computed by computeTrackPlacements above -- not just row order.
    let posCls, posText;
    if (id === sim.winnerId) { posCls = 'pos-win'; posText = '1st'; }
    else if (sim.runnerUpIds.includes(id)) { posCls = 'pos-ru'; posText = 'RU'; }
    else { posCls = 'pos-other'; posText = ordinal(placements[id]); }
    // Item 4: queen's circle avatar to the left of her name.
    const nameCell = `<td class="track-name-col"><div class="track-name-inner">
      <span class="track-pos-tag ${posCls}">${esc(posText)}</span>
      <span class="display track-avatar avatar ${avatarClass(idx)}">${esc(initialsOf(name))}</span>
      <span>${esc(name)}</span>
    </div></td>`;
    return `<tr>${nameCell}${cells}</tr>`;
  }).join('');
}

function render() {
  const setupPage = document.getElementById('page-setup');
  const resultsPage = document.getElementById('page-results');
  if (state.view === 'setup') {
    setupPage.classList.remove('hidden');
    resultsPage.classList.add('hidden');
    renderSetup();
  } else {
    setupPage.classList.add('hidden');
    resultsPage.classList.remove('hidden');
    renderResults();
  }
}

function renderSetup() {
  const d = computeDerived();
  const tc = state.twistConfig;

  document.querySelectorAll('#mode-toggle .mode-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.mode === state.mode);
  });

  const hint = document.getElementById('replica-hint');
  hint.classList.toggle('hidden', !d.isReplicaMode);
  if (d.isReplicaMode) {
    document.getElementById('replica-hint-label').textContent = state.mode === 'replica5' ? 'Season 5' : 'Season 6';
  }

  ['immunity', 'split', 'doubleElimination', 'doubleSave', 'semifinal'].forEach((key) => {
    const row = document.querySelector(`.twist-row[data-twist="${key}"]`);
    const cfg = tc[key];
    row.classList.toggle('on', cfg.on);
    row.querySelector('.checkbox').classList.toggle('checked', cfg.on);
  });

  setFieldValue('immunity', 'endsAfterEpisode', tc.immunity.endsAfterEpisode);
  setFieldValue('split', 'groups', tc.split.groups);

  ['doubleElimination', 'doubleSave'].forEach((key) => {
    const t = tc[key];
    setFieldValue(key, 'occurrences', t.occurrences);
    setFieldValue(key, 'episode', t.episode);
    setFieldValue(key, 'probability', t.probability);
    setFieldValue(key, 'fireMode', t.fireMode);
    const row = document.querySelector(`.twist-row[data-twist="${key}"]`);
    row.querySelector('.field-occurrences').classList.toggle('hidden', t.fireMode === 'forced');
    row.querySelector('.field-episode').classList.toggle('hidden', t.fireMode !== 'forced');
    row.querySelector('.field-probability').classList.toggle('hidden', t.fireMode !== 'custom');
  });

  const castSizeInput = document.getElementById('cast-size-input');
  castSizeInput.disabled = d.isReplicaMode;
  setInputValue(castSizeInput, d.isReplicaMode ? d.targetSize : state.customCastSize);

  document.getElementById('progress-count').textContent = `${d.selectedCount} / ${d.targetSize}`;
  document.getElementById('progress-fill').style.width = `${d.targetSize > 0 ? Math.min(100, Math.round(d.selectedCount / d.targetSize * 100)) : 0}%`;

  const continueBtn = document.getElementById('continue-btn');
  continueBtn.classList.toggle('ready', d.readyToContinue);
  continueBtn.disabled = d.hasMismatch;

  const mismatchEl = document.getElementById('mismatch-msg');
  mismatchEl.classList.toggle('hidden', !d.hasMismatch);
  mismatchEl.textContent = d.mismatchMessage;

  const selectedIdSet = new Set(state.selected);
  const selectedQueens = ALL_QUEENS.filter((qn) => selectedIdSet.has(qn.id));
  const castCardsEl = document.getElementById('cast-cards');
  document.getElementById('no-cast-msg').classList.toggle('hidden', selectedQueens.length > 0);
  castCardsEl.classList.toggle('hidden', selectedQueens.length === 0);
  if (selectedQueens.length) castCardsEl.innerHTML = selectedQueens.map(buildCastCardHTML).join('');

  const splitGroupsSection = document.getElementById('split-groups-section');
  const showSplitGroups = state.twistConfig.split.on && selectedQueens.length > 0;
  splitGroupsSection.classList.toggle('hidden', !showSplitGroups);
  if (showSplitGroups) {
    // Drop any picks left over from a queen who's since been removed from the cast.
    state.splitPicked = (state.splitPicked || []).filter((id) => selectedIdSet.has(id));
    const numGroups = Math.max(2, state.twistConfig.split.groups || 2);
    document.getElementById('split-groups-toolbar').innerHTML = buildSplitGroupsToolbarHTML(numGroups, state.splitPicked.length);
    document.getElementById('split-groups-columns').innerHTML = buildSplitGroupsColumnsHTML(selectedQueens, state.twistConfig.split);
  }

  setInputValue(document.getElementById('search-input'), state.query);
  setInputValue(document.getElementById('sort-select'), state.sortBy);
  setInputValue(document.getElementById('country-select'), state.filterCountry);
  setInputValue(document.getElementById('season-select'), state.filterSeason);

  // Item 7: a queen selected into Current Cast is popped out of the Full
  // Roster entirely (not just highlighted) -- she reappears here the moment
  // she's removed from the cast.
  let filtered = getFilteredQueens().filter((qn) => !selectedIdSet.has(qn.id));
  filtered = filtered.slice().sort((a, b) =>
    state.sortBy === 'season' ? (a.season - b.season || a.name.localeCompare(b.name)) : a.name.localeCompare(b.name)
  );

  document.getElementById('queen-count').textContent = `${filtered.length} queens`;

  const rosterHtml = filtered.length
    ? filtered.map((qn) => buildQueenCardHTML(qn, false)).join('')
    : `<div class="empty-msg">No queens match &ldquo;${esc(state.query)}&rdquo;.</div>`;
  rebuildWithScroll(document.getElementById('roster-grid'), rosterHtml);
}

function renderResults() {
  const sim = state.simResult;
  const namesById = {};
  ALL_QUEENS.forEach((q) => { namesById[q.id] = q.name; });

  if (!sim) {
    document.getElementById('results-subtitle').textContent = '';
    document.getElementById('episodes-list').innerHTML = '<div class="empty-msg">No results yet.</div>';
    document.getElementById('winner-banner').classList.add('hidden');
    document.getElementById('track-table-head').innerHTML = '';
    document.getElementById('track-table-body').innerHTML = '';
    return;
  }

  const modeLabel = state.mode === 'replica5' ? 'Season 5 Replica' : state.mode === 'replica6' ? 'Season 6 Replica' : 'Custom Season';
  document.getElementById('results-subtitle').textContent = `${modeLabel} — ${sim.episodes.length} episodes simulated`;
  document.getElementById('episodes-list').innerHTML = sim.episodes.map((ep) => buildEpisodeHTML(ep, namesById)).join('');
  renderTrackRecord(sim, state.lastCast, namesById);

  const banner = document.getElementById('winner-banner');
  if (sim.winnerId) {
    banner.classList.remove('hidden');
    const winnerName = namesById[sim.winnerId] || sim.winnerId;
    const winnerIdx = AVATAR_INDEX_BY_ID[sim.winnerId] ?? 0;
    const winnerAvatar = document.getElementById('winner-avatar');
    winnerAvatar.className = `winner-avatar avatar ${avatarClass(winnerIdx)}`;
    winnerAvatar.textContent = initialsOf(winnerName);
    document.getElementById('winner-name').textContent = winnerName;
    document.getElementById('runner-ups').innerHTML = sim.runnerUpIds.map((id) => {
      const idx = AVATAR_INDEX_BY_ID[id] ?? 0;
      const name = namesById[id] || id;
      return `<div class="runner-up">
        <div class="display runner-up-avatar avatar ${avatarClass(idx)}">${esc(initialsOf(name))}</div>
        <div class="runner-up-name">${esc(name)}</div>
      </div>`;
    }).join('');
  } else {
    banner.classList.add('hidden');
  }
}

// ===========================================================================
// EVENT HANDLING (delegated on the persistent #root shell)
// ===========================================================================

function pruneSplitManualGroups(splitTwist) {
  const numGroups = Math.max(2, splitTwist.groups || 2);
  const labels = ['A', 'B', 'C', 'D'].slice(0, numGroups);
  const manual = splitTwist.manualGroups || {};
  Object.keys(manual).forEach((id) => { if (!labels.includes(manual[id])) delete manual[id]; });
  splitTwist.manualGroups = manual;
}

function attachHandlers() {
  const root = document.getElementById('root');

  root.onclick = (e) => {
    const el = e.target.closest('[data-action]');
    if (!el) return;
    const action = el.dataset.action;
    if (action === 'toggleQueen') {
      const id = el.dataset.id;
      const i = state.selected.indexOf(id);
      if (i === -1) state.selected.push(id); else state.selected.splice(i, 1);
      render();
    } else if (action === 'removeQueen') {
      state.selected = state.selected.filter((x) => x !== el.dataset.id);
      if (state.editingCastId === el.dataset.id) state.editingCastId = null;
      render();
    } else if (action === 'addAllFiltered') {
      const filteredIds = getFilteredQueens().map((qn) => qn.id);
      filteredIds.forEach((id) => { if (!state.selected.includes(id)) state.selected.push(id); });
      render();
    } else if (action === 'setVersion') {
      const qn = ALL_QUEENS.find((q) => q.id === el.dataset.id);
      if (qn) setActiveVersion(qn, Number(el.dataset.vidx));
      render();
    } else if (action === 'toggleCastEdit') {
      const id = el.dataset.id;
      state.editingCastId = state.editingCastId === id ? null : id;
      render();
    } else if (action === 'setVersionAndClose') {
      const qn = ALL_QUEENS.find((q) => q.id === el.dataset.id);
      if (qn) setActiveVersion(qn, Number(el.dataset.vidx));
      state.editingCastId = null;
      render();
    } else if (action === 'setMode') {
      const mode = el.dataset.mode;
      state.mode = mode;
      const preset = REPLICA_PRESETS[mode];
      if (preset) {
        state.customCastSize = preset.castSize;
        state.twistConfig = JSON.parse(JSON.stringify(preset.twistConfig));
      }
      render();
    } else if (action === 'toggleTwist') {
      const key = el.dataset.key;
      state.mode = 'custom';
      state.twistConfig[key].on = !state.twistConfig[key].on;
      if (key === 'split') { state.twistConfig.split.manualGroups = {}; state.splitPicked = []; }
      render();
    } else if (action === 'clearCast') {
      state.selected = [];
      state.splitPicked = [];
      state.editingCastId = null;
      render();
    } else if (action === 'randomCast') {
      // Entirely fresh random cast at the currently-configured cast size --
      // replaces whatever's selected, and gives multi-version queens a
      // random version rather than always defaulting to their earliest one.
      const targetSize = computeDerived().targetSize;
      const shuffledIds = shuffleIds(ALL_QUEENS.map((q) => q.id), Math.random);
      const castIds = shuffledIds.slice(0, Math.max(0, Math.min(targetSize, shuffledIds.length)));
      castIds.forEach((id) => {
        const qn = ALL_QUEENS.find((q) => q.id === id);
        if (qn && qn.versions.length > 1) {
          setActiveVersion(qn, Math.floor(Math.random() * qn.versions.length));
        }
      });
      state.selected = castIds;
      state.splitPicked = [];
      state.editingCastId = null;
      render();
    } else if (action === 'runSimulation') {
      if (el.disabled) return;
      const cast = ALL_QUEENS.filter((q) => state.selected.includes(q.id))
        .map((q) => ({ id: q.id, name: q.name, charisma: q.c, uniqueness: q.u, nerve: q.n, talent: q.t }));
      const seed = Math.floor(Math.random() * 1e9);
      state.lastCast = cast;
      state.simResult = runSeason(cast, state.twistConfig, state.mode, seed);
      state.view = 'results';
      render();
    } else if (action === 'backToSetup') {
      state.view = 'setup';
      render();
    } else if (action === 'toggleSplitPick') {
      const id = el.dataset.id;
      const picked = state.splitPicked || (state.splitPicked = []);
      const i = picked.indexOf(id);
      if (i === -1) picked.push(id); else picked.splice(i, 1);
      render();
    } else if (action === 'assignSplitGroup') {
      const label = el.dataset.label; // '' means Unassign
      const picked = state.splitPicked || [];
      if (!picked.length) return;
      const manual = state.twistConfig.split.manualGroups || (state.twistConfig.split.manualGroups = {});
      picked.forEach((id) => { if (label) manual[id] = label; else delete manual[id]; });
      state.splitPicked = [];
      render();
    } else if (action === 'clearSplitPick') {
      state.splitPicked = [];
      render();
    } else if (action === 'randomizeSplitGroups') {
      const numGroups = Math.max(2, state.twistConfig.split.groups || 2);
      const labels = ['A', 'B', 'C', 'D'].slice(0, numGroups);
      const shuffled = shuffleIds(state.selected.slice(), Math.random);
      const perGroup = Math.ceil(shuffled.length / numGroups);
      const manual = {};
      labels.forEach((label, i) => {
        shuffled.slice(i * perGroup, (i + 1) * perGroup).forEach((id) => { manual[id] = label; });
      });
      state.twistConfig.split.manualGroups = manual;
      state.splitPicked = [];
      render();
    } else if (action === 'scrollToTop') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  root.oninput = (e) => {
    const el = e.target.closest('[data-action]');
    if (!el) return;
    const action = el.dataset.action;
    if (action === 'setQuery') { state.query = el.value; render(); }
    else if (action === 'setCastSize') {
      state.mode = 'custom';
      state.customCastSize = el.value === '' ? '' : (parseInt(el.value, 10) || '');
      render();
    } else if (action === 'twistField') {
      const key = el.dataset.key, field = el.dataset.field;
      state.mode = 'custom';
      let val = el.value;
      if (el.type === 'number') val = val === '' ? '' : (parseInt(val, 10) || '');
      state.twistConfig[key][field] = val;
      if (key === 'split' && field === 'groups') pruneSplitManualGroups(state.twistConfig.split);
      render();
    }
  };

  root.onchange = (e) => {
    const el = e.target.closest('[data-action]');
    if (!el) return;
    const action = el.dataset.action;
    if (action === 'setSortBy') { state.sortBy = el.value; render(); }
    else if (action === 'setFilterCountry') { state.filterCountry = el.value; render(); }
    else if (action === 'setFilterSeason') { state.filterSeason = el.value; render(); }
    else if (action === 'twistField') {
      const key = el.dataset.key, field = el.dataset.field;
      state.mode = 'custom';
      state.twistConfig[key][field] = el.value;
      if (key === 'split' && field === 'groups') pruneSplitManualGroups(state.twistConfig.split);
      render();
    } else if (action === 'setCastSize') {
      const parsed = parseInt(el.value, 10);
      state.customCastSize = isNaN(parsed) ? 8 : Math.max(8, Math.min(24, parsed));
      render();
    }
  };
}

// Back-to-top button: fades in once the page has scrolled down a bit,
// rather than sitting on screen (and in the way) right from the start.
function initScrollTopButton() {
  const btn = document.getElementById('scroll-top-btn');
  if (!btn) return;
  const SHOW_AFTER_PX = 400;
  window.addEventListener('scroll', () => {
    btn.classList.toggle('visible', window.scrollY > SHOW_AFTER_PX);
  }, { passive: true });
}

// Quick-nav in the sticky top bar: highlights the link for whichever setup
// section (Twists / Current Cast / Full Roster) is currently under the bar.
// The links themselves are plain #anchors (smooth-scrolled via CSS).
function initSetupNav() {
  const links = Array.from(document.querySelectorAll('.topnav-link'));
  if (!links.length) return;
  const targets = links.map((l) => document.getElementById(l.dataset.target));
  const bar = document.getElementById('setup-topbar');
  const update = () => {
    const offset = (bar ? bar.offsetHeight : 0) + 24;
    let active = -1;
    targets.forEach((t, i) => { if (t && t.getBoundingClientRect().top <= offset) active = i; });
    if (window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 2) active = targets.length - 1;
    links.forEach((l, i) => l.classList.toggle('active', i === active));
  };
  window.addEventListener('scroll', update, { passive: true });
  window.addEventListener('resize', update);
  update();
}

initCountryOptions();
initSeasonOptions();
attachHandlers();
initScrollTopButton();
initSetupNav();
render();
