// AUTO-GENERATED by build.js -- do not hand-edit.
// Run `node build.js` after refreshing the CSVs in sheet-data/ to regenerate this
// and dragg_data.json together.
const DRAGG_DATA = {
  "_comment": "Generated by build.js from CSV exports of the 'Drag Race: The Simulator' Google Sheet (see the comment at the top of build.js for the update workflow). Never hand-edit this file or dragg_data.js -- edit the sheet, re-export the CSVs into sheet-data/, and run `node build.js`.",
  "countries": {
    "US": "United States",
    "THA": "Thailand",
    "UK": "United Kingdom",
    "CAN": "Canada",
    "HOL": "Holland (The Netherlands)",
    "DU": "Down Under (Australia & New Zealand)",
    "ESP": "España",
    "ITL": "Italy",
    "FRA": "France",
    "PHI": "Philippines",
    "BEL": "Belgique (Belgium)",
    "SVE": "Sveridge (Sweden)",
    "MEX": "México",
    "BRA": "Brazil",
    "GER": "Germany"
  },
  "queens": [
    {
      "qid": "00060",
      "name": "Adore Delano",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 5.91,
          "uniqueness": 6,
          "nerve": 6.01,
          "talent": 5.7
        }
      ]
    },
    {
      "qid": "00046",
      "name": "Alaska",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 6.23,
          "uniqueness": 6.92,
          "nerve": 5.92,
          "talent": 5.55
        }
      ]
    },
    {
      "qid": "00047",
      "name": "Alyssa Edwards",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 3.37,
          "uniqueness": 3.44,
          "nerve": 3.92,
          "talent": 4.66
        }
      ]
    },
    {
      "qid": "00061",
      "name": "April Carrión",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 0.91,
          "uniqueness": 5.25,
          "nerve": 0.63,
          "talent": 2.3
        }
      ]
    },
    {
      "qid": "00062",
      "name": "Ben DeLaCreme",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 4.83,
          "uniqueness": 5.04,
          "nerve": 4.99,
          "talent": 5.69
        }
      ]
    },
    {
      "qid": "00063",
      "name": "Bianca Del Rio",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 6.71,
          "uniqueness": 7.83,
          "nerve": 6.49,
          "talent": 7.11
        }
      ]
    },
    {
      "qid": "00048",
      "name": "Coco Montrese",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.21,
          "uniqueness": 4.01,
          "nerve": 3.8,
          "talent": 3.2
        }
      ]
    },
    {
      "qid": "00064",
      "name": "Courtney Act",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 5.81,
          "uniqueness": 4.93,
          "nerve": 6.17,
          "talent": 6.06
        }
      ]
    },
    {
      "qid": "00065",
      "name": "Darienne Lake",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 4.15,
          "uniqueness": 2.63,
          "nerve": 4.09,
          "talent": 3.66
        }
      ]
    },
    {
      "qid": "00049",
      "name": "Detox",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.68,
          "uniqueness": 3.27,
          "nerve": 4.61,
          "talent": 4.38
        }
      ]
    },
    {
      "qid": "00066",
      "name": "Gia Gunn",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 2.88,
          "uniqueness": 4.69,
          "nerve": 3.38,
          "talent": 4.78
        }
      ]
    },
    {
      "qid": "00050",
      "name": "Honey Mahogany",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.23,
          "uniqueness": 5.02,
          "nerve": 3.63,
          "talent": 3.84
        }
      ]
    },
    {
      "qid": "00051",
      "name": "Ivy Winters",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.13,
          "uniqueness": 4.29,
          "nerve": 5.01,
          "talent": 6.24
        }
      ]
    },
    {
      "qid": "00052",
      "name": "Jade Jolie",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.66,
          "uniqueness": 4.2,
          "nerve": 4.01,
          "talent": 3.73
        }
      ]
    },
    {
      "qid": "00053",
      "name": "Jinkx Monsoon",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 6.6,
          "uniqueness": 5.03,
          "nerve": 6.46,
          "talent": 5.9
        }
      ]
    },
    {
      "qid": "00067",
      "name": "Joslyn Fox",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 3.94,
          "uniqueness": 3.2,
          "nerve": 4.17,
          "talent": 4.16
        }
      ]
    },
    {
      "qid": "00068",
      "name": "Kelly Mantle",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 0,
          "uniqueness": 0,
          "nerve": 0,
          "talent": 0
        }
      ]
    },
    {
      "qid": "00069",
      "name": "Laganja Estranja",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 4.29,
          "uniqueness": 4.79,
          "nerve": 4.34,
          "talent": 4.51
        }
      ]
    },
    {
      "qid": "00054",
      "name": "Lineysha Sparx",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.95,
          "uniqueness": 5.11,
          "nerve": 5.01,
          "talent": 5.87
        }
      ]
    },
    {
      "qid": "00070",
      "name": "Magnolia Crawford",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 0,
          "uniqueness": 0,
          "nerve": 0,
          "talent": 0
        }
      ]
    },
    {
      "qid": "00071",
      "name": "Milk",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 3.89,
          "uniqueness": 4.76,
          "nerve": 3.73,
          "talent": 4.39
        }
      ]
    },
    {
      "qid": "00055",
      "name": "Monica Beverly Hillz",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 0.6,
          "uniqueness": 4.03,
          "nerve": 0.61,
          "talent": 2.25
        }
      ]
    },
    {
      "qid": "00056",
      "name": "Penny Tration",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 0,
          "uniqueness": 0,
          "nerve": 0,
          "talent": 0
        }
      ]
    },
    {
      "qid": "00057",
      "name": "Roxxxy Andrews",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 4.9,
          "uniqueness": 6.84,
          "nerve": 5.11,
          "talent": 6.27
        }
      ]
    },
    {
      "qid": "00058",
      "name": "Serena ChaCha",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 0.04,
          "uniqueness": 0.89,
          "nerve": 0.05,
          "talent": 0.55
        }
      ]
    },
    {
      "qid": "00072",
      "name": "Trinity K. Bonet",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 4.14,
          "uniqueness": 5.01,
          "nerve": 3.57,
          "talent": 3.66
        }
      ]
    },
    {
      "qid": "00073",
      "name": "Vivacious",
      "country": "US",
      "versions": [
        {
          "sid": "000006",
          "season": 6,
          "versionName": "Regular",
          "seasonLabel": "Season 6",
          "shortLabel": "S6",
          "charisma": 0.04,
          "uniqueness": 0.89,
          "nerve": 0.05,
          "talent": 0.55
        }
      ]
    },
    {
      "qid": "00059",
      "name": "Vivienne Pinay",
      "country": "US",
      "versions": [
        {
          "sid": "000005",
          "season": 5,
          "versionName": "Regular",
          "seasonLabel": "Season 5",
          "shortLabel": "S5",
          "charisma": 3.85,
          "uniqueness": 4.9,
          "nerve": 3.31,
          "talent": 3.63
        }
      ]
    }
  ],
  "challengeCategories": {
    "acting": {
      "weights": {
        "acting": 7,
        "comedy": 3
      },
      "probability": 5.88,
      "grouping": 1
    },
    "advert": {
      "weights": {
        "branding": 6,
        "comedy": 3,
        "improv": 1
      },
      "probability": 5.88,
      "grouping": 1
    },
    "ball_classic": {
      "weights": {
        "dance": 1,
        "design": 4.5,
        "runway": 4.5
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "ball_modern": {
      "weights": {
        "design": 5,
        "runway": 5
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "choreo": {
      "weights": {
        "acting": 1,
        "dance": 8,
        "lip_sync": 1
      },
      "probability": 5.88,
      "grouping": 1
    },
    "design": {
      "weights": {
        "design": 9,
        "makeover": 1
      },
      "probability": 4.71,
      "grouping": 0.8
    },
    "design_rooms": {
      "weights": {
        "branding": 2,
        "comedy": 3,
        "design": 3,
        "improv": 2
      },
      "probability": 1.18,
      "grouping": 0.2
    },
    "girl_groups": {
      "weights": {
        "branding": 2,
        "dance": 4,
        "lip_sync": 1,
        "runway": 1,
        "vocal": 2
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "improv": {
      "weights": {
        "acting": 6,
        "comedy": 3,
        "improv": 1
      },
      "probability": 5.88,
      "grouping": 1
    },
    "lip_sync": {
      "weights": {
        "dance": 1,
        "lip_sync": 9
      },
      "probability": 5.88,
      "grouping": 1
    },
    "make_over": {
      "weights": {
        "design": 1,
        "makeover": 9
      },
      "probability": 4.71,
      "grouping": 0.8
    },
    "make_over_girl_groups": {
      "weights": {
        "branding": 1,
        "dance": 3,
        "makeover": 4,
        "runway": 1,
        "vocal": 1
      },
      "probability": 1.18,
      "grouping": 0.2
    },
    "music_video": {
      "weights": {
        "acting": 2,
        "branding": 1,
        "comedy": 1,
        "dance": 3,
        "lip_sync": 2,
        "runway": 1
      },
      "probability": 0,
      "grouping": 0
    },
    "photo_shoot": {
      "weights": {
        "branding": 4,
        "design": 2,
        "makeover": 2,
        "runway": 2
      },
      "probability": 5.88,
      "grouping": 1
    },
    "roast": {
      "weights": {
        "comedy": 8,
        "improv": 2
      },
      "probability": 4.71,
      "grouping": 0.8
    },
    "roast_rumix": {
      "weights": {
        "comedy": 4,
        "dance": 2,
        "lip_sync": 2,
        "runway": 1,
        "vocal": 1
      },
      "probability": 1.18,
      "grouping": 0.2
    },
    "rumix": {
      "weights": {
        "branding": 1,
        "dance": 4,
        "lip_sync": 2,
        "runway": 1,
        "vocal": 2
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "runway": {
      "weights": {
        "makeover": 1,
        "runway": 9
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "runway_design": {
      "weights": {
        "design": 4.5,
        "makeover": 1,
        "runway": 4.5
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "rusical_lip_sync": {
      "weights": {
        "acting": 1,
        "comedy": 1,
        "dance": 3,
        "lip_sync": 5
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "rusical_live": {
      "weights": {
        "acting": 1,
        "comedy": 1,
        "dance": 3,
        "vocal": 5
      },
      "probability": 2.94,
      "grouping": 0.5
    },
    "rusical_rumix": {
      "weights": {
        "acting": 0.5,
        "branding": 0.5,
        "comedy": 0.5,
        "dance": 3.5,
        "lip_sync": 3.5,
        "runway": 0.5,
        "vocal": 1
      },
      "probability": 0,
      "grouping": 0
    },
    "singing": {
      "weights": {
        "improv": 3,
        "vocal": 7
      },
      "probability": 5.88,
      "grouping": 1
    },
    "snatch_game": {
      "weights": {
        "comedy": 4,
        "improv": 6
      },
      "probability": 5.88,
      "grouping": 1
    },
    "stand_up": {
      "weights": {
        "branding": 1,
        "comedy": 7,
        "improv": 2
      },
      "probability": 5.88,
      "grouping": 1
    },
    "talent_show": {
      "weights": {
        "acting": 1,
        "branding": 1,
        "comedy": 1,
        "dance": 1,
        "design": 1,
        "improv": 1,
        "lip_sync": 1,
        "makeover": 1,
        "runway": 1,
        "vocal": 1
      },
      "probability": 0,
      "grouping": 0
    },
    "talk_show": {
      "weights": {
        "comedy": 3,
        "hosting": 5,
        "improv": 2
      },
      "probability": 5.88,
      "grouping": 1
    }
  },
  "episodeCategories": {
    "5": [
      {
        "ep": 1,
        "category": "design",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 2,
        "category": "acting",
        "work": "groups",
        "groupSize": 3,
        "judging": "uniform"
      },
      {
        "ep": 3,
        "category": "improv",
        "work": "groups",
        "groupSize": 2,
        "judging": "individual"
      },
      {
        "ep": 4,
        "category": "choreo",
        "work": "groups",
        "groupSize": 2,
        "judging": "individual"
      },
      {
        "ep": 5,
        "category": "snatch_game",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 6,
        "category": "singing",
        "work": "groups",
        "groupSize": 3,
        "judging": "individual"
      },
      {
        "ep": 7,
        "category": "roast",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 8,
        "category": "advert",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 9,
        "category": "acting",
        "work": "groups",
        "groupSize": 2,
        "judging": "individual"
      },
      {
        "ep": 10,
        "category": "make_over",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 11,
        "category": "ball_classic",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 12,
        "category": "music_video",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 13,
        "category": "final",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      }
    ],
    "6": [
      {
        "ep": 1,
        "category": "design",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 2,
        "category": "design",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 3,
        "category": "acting",
        "work": "groups",
        "groupSize": 2,
        "judging": "uniform"
      },
      {
        "ep": 4,
        "category": "rusical_live",
        "work": "groups",
        "groupSize": 2,
        "judging": "individual"
      },
      {
        "ep": 5,
        "category": "snatch_game",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 6,
        "category": "girl_groups",
        "work": "groups",
        "groupSize": 2,
        "judging": "individual"
      },
      {
        "ep": 7,
        "category": "advert",
        "work": "pairs",
        "groupSize": 2,
        "judging": "uniform"
      },
      {
        "ep": 8,
        "category": "stand_up",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 9,
        "category": "talk_show",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 10,
        "category": "make_over",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 11,
        "category": "ball_classic",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 12,
        "category": "music_video",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      },
      {
        "ep": 13,
        "category": "final",
        "work": "individual",
        "groupSize": null,
        "judging": "individual"
      }
    ]
  },
  "cuntScores": {
    "acting": {
      "charisma": 1,
      "uniqueness": 0,
      "nerve": 1,
      "talent": 1.5
    },
    "branding": {
      "charisma": 1.5,
      "uniqueness": 1.5,
      "nerve": 1,
      "talent": 0
    },
    "comedy": {
      "charisma": 1.5,
      "uniqueness": 1,
      "nerve": 1,
      "talent": 0.5
    },
    "dance": {
      "charisma": 0.5,
      "uniqueness": 0,
      "nerve": 1,
      "talent": 1.5
    },
    "design": {
      "charisma": 0,
      "uniqueness": 2.5,
      "nerve": 0,
      "talent": 1.5
    },
    "hosting": {
      "charisma": 1,
      "uniqueness": 0,
      "nerve": 1,
      "talent": 0
    },
    "improv": {
      "charisma": 1,
      "uniqueness": 0.5,
      "nerve": 1,
      "talent": 0.5
    },
    "lip_sync": {
      "charisma": 2,
      "uniqueness": 0.5,
      "nerve": 1.5,
      "talent": 1
    },
    "makeover": {
      "charisma": 0.5,
      "uniqueness": 1.5,
      "nerve": 0.5,
      "talent": 1
    },
    "runway": {
      "charisma": 1,
      "uniqueness": 2.5,
      "nerve": 1,
      "talent": 0.5
    },
    "vocal": {
      "charisma": 0,
      "uniqueness": 0,
      "nerve": 1,
      "talent": 2
    }
  }
};
